apiVersion: apps/v1
kind: Deployment
metadata:
  name: diploma-app
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: diploma-app
  template:
    metadata:
      labels:
        app: diploma-app
    spec:
      containers:
        - name: nginx
          image: furious992/diploma-app:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: diploma-app-svc
  namespace: app
spec:
  type: LoadBalancer
  selector:
    app: diploma-app
  ports:
    - name: http
      port: 80
      targetPort: 80
